name: client tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  test:

    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore .src/Korpi/Client.Tests/ClientTests.csproj
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal .src/Korpi/Client.Tests/ClientTests.csproj
